#!/usr/bin/env python3
"""
Reorganize sweep_run_* GRU log pickles into per-run folders and emit per-run threshold CSVs.

The script expects:
  * A directory that contains files such as ``sweep_run_0_dp1_inter_h1.pkl``.
  * A ``sweep.csv`` file generated by optimize_delta_thresholds.py.

For every run index it creates ``run_<idx>`` inside the PKL directory, moves and renames the
pickles (compressing their names to ``<component>_{x|h}.pkl``), and writes a ``thresholds.csv``
with only the threshold columns for that run (renaming the per-GRU columns to match the files).
"""

from __future__ import annotations

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, MutableMapping, Sequence


PKL_PATTERN = re.compile(r"^sweep_run_(\d+)_(.+)\.pkl$")


def compress_component_name(component: str) -> str:
    """
    Turn names like ``dp1_inter_h1`` into ``dp1inter1_h``.
    The suffix after the last underscore is expected to start with ``x`` or ``h``.
    """
    parts = component.split("_")
    if len(parts) < 2:
        return component
    base = "".join(parts[:-1])
    tail = parts[-1]
    if not tail:
        return base
    dtype = tail[0]
    if dtype not in ("x", "h"):
        # Unexpected suffix, fall back to base_last convention.
        return f"{base}_{tail}"
    suffix = tail[1:] if len(tail) > 1 else ""
    return f"{base}{suffix}_{dtype}"


def column_to_component(column: str) -> str | None:
    """Map sweep.csv column names to the component tokens used in PKL filenames."""
    tokens = column.split("_")
    if not tokens:
        return None

    head = tokens[0]
    if head in ("encoder", "decoder"):
        if len(tokens) < 4 or tokens[1] != "tra":
            return None
        prefix = "enc" if head == "encoder" else "dec"
        idx = tokens[2]
        dtype = tokens[3]
        return f"{prefix}_tra{idx}_{dtype}"

    if head.startswith("dpgrnn") and len(tokens) >= 4:
        dp_idx = head[-1]
        stage = tokens[1]
        rnn = tokens[2]
        dtype = tokens[3]
        if not rnn.startswith("rnn"):
            return None
        lane = rnn[3:]
        return f"dp{dp_idx}_{stage}_{dtype}{lane}"

    return None


def load_threshold_rows(csv_path: Path) -> tuple[List[MutableMapping[str, str]], List[str], Dict[str, str]]:
    """Read sweep.csv and return (rows, threshold_columns, rename_map)."""
    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        fieldnames = reader.fieldnames or []

    threshold_columns: List[str] = []
    for name in fieldnames:
        if name == "metric":
            break
        threshold_columns.append(name)
    if not threshold_columns:
        for name in fieldnames:
            if name.startswith("threshold") or name.startswith(("encoder_", "decoder_", "dpgrnn")):
                threshold_columns.append(name)

    rename_map: Dict[str, str] = {}
    for col in threshold_columns:
        component = column_to_component(col)
        if component:
            rename_map[col] = compress_component_name(component)
    # Rename global columns for readability.
    rename_map.setdefault("threshold_global", "global")
    rename_map.setdefault("threshold_x", "global_x")
    rename_map.setdefault("threshold_h", "global_h")
    return rows, threshold_columns, rename_map


def write_threshold_csv(
    target_dir: Path,
    row: MutableMapping[str, str],
    columns: Sequence[str],
    rename_map: Dict[str, str],
) -> None:
    ordered_names = [rename_map.get(col, col) for col in columns]
    data = {rename_map.get(col, col): row.get(col, "") for col in columns}
    csv_path = target_dir / "thresholds.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=ordered_names)
        writer.writeheader()
        writer.writerow(data)


def reorganize(pkls_dir: Path, rows: List[MutableMapping[str, str]], threshold_cols: List[str], rename_map: Dict[str, str]) -> None:
    entries: Dict[int, List[tuple[str, Path]]] = defaultdict(list)
    for path in pkls_dir.glob("sweep_run_*_*.pkl"):
        match = PKL_PATTERN.match(path.name)
        if not match:
            continue
        run_id = int(match.group(1))
        component = match.group(2)
        entries[run_id].append((component, path))

    if not entries:
        print(f"No sweep_run_*.pkl files found in {pkls_dir}")
        return

    for run_id in sorted(entries.keys()):
        if run_id >= len(rows):
            raise ValueError(f"Run {run_id} not present in the {len(rows)} rows of the sweep CSV")
        run_dir = pkls_dir / f"run_{run_id}"
        run_dir.mkdir(parents=True, exist_ok=True)

        for component, path in entries[run_id]:
            new_base = compress_component_name(component)
            target = run_dir / f"{new_base}{path.suffix}"
            if target.exists():
                raise FileExistsError(f"Target {target} already exists")
            path.rename(target)

        write_threshold_csv(run_dir, rows[run_id], threshold_cols, rename_map)
        print(f"Run {run_id}: moved {len(entries[run_id])} files -> {run_dir}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Group sweep_run_* pickles into per-run folders and emit per-run threshold CSVs.")
    parser.add_argument(
        "--pkls-dir",
        type=Path,
        default=Path("logs/threshold_opt/pkls"),
        help="Directory that contains sweep_run_*_*.pkl files (default: logs/threshold_opt/pkls).",
    )
    parser.add_argument(
        "--sweep-csv",
        type=Path,
        default=Path("logs/threshold_opt/sweep.csv"),
        help="Path to sweep.csv generated by optimize_delta_thresholds.py.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    pkls_dir = args.pkls_dir.expanduser().resolve()
    csv_path = args.sweep_csv.expanduser().resolve()
    if not pkls_dir.is_dir():
        raise FileNotFoundError(f"PKL directory {pkls_dir} does not exist")
    if not csv_path.is_file():
        raise FileNotFoundError(f"CSV file {csv_path} does not exist")
    rows, threshold_cols, rename_map = load_threshold_rows(csv_path)
    reorganize(pkls_dir, rows, threshold_cols, rename_map)


if __name__ == "__main__":
    main()
