test_dataset:
  noisy_dir: /home/terzano/Desktop/NNs/SEtrain/data/voicebank-demand-16k/test/noisy
  clean_dir: /home/terzano/Desktop/NNs/SEtrain/data/voicebank-demand-16k/test/clean

network:
  exp_path: /home/terzano/Desktop/NNs/gtcrn-qat/SEtrain/experiments/standard_qat_no_distill/run_2026-03-04-09h56m
  config: ${network.exp_path}/config.yaml
  ckpt_name: best_model_230
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: ${network.exp_path}/${network.ckpt_name}/plots
  use_int8: True
