test_dataset:
  noisy_dir: data/voicebank-demand-16k/valid/noisy
  clean_dir: data/voicebank-demand-16k/valid/clean

network:
  config: configs/cfg_train.yaml
  checkpoint: experiments/td_gtcrn/checkpoints/model_001.tar
  enh_folder: runs/infer_outputs
  ckpt_name: model_001
  exp_path: experiments/td_gtcrn
