test_dataset: 
  # If you want to use explicit folders, set noisy_dir and clean_dir.
  # Otherwise, use `dataset` below to prepare/load the VoiceBank-DEMAND dataset via the dataloader.
  noisy_dir: null
  clean_dir: null

dataset:
  # Options forwarded to VoiceBankDemandDataset in dataloader.py
  # If dataset_root is not provided, the dataloader will use the bundled DEFAULT_DATA_ROOT
  dataset_root: null
  length_in_seconds: 10
  num_data_tot: -1
  num_data_per_epoch: -1
  random_start_point: False
  train: False
  split: test

network:
  exp_path: /home/terzano/Desktop/NNs/SEtrain/experiments/gtcrn_2025-10-01-16h05m
  config: ${network.exp_path}/config.yaml
  ckpt_name: best_model_111
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: /home/terzano/Desktop/NNs/SEtrain/logs/near-search-2/enhanced
  # Optional overrides for DeltaGRU inference; leave as null to use the experiment defaults.
  use_delta_gru: true

  # These two are global thresholds; if you want to set per-layer thresholds, leave these as null.
  delta_gru_threshold_x: 10
  delta_gru_threshold_h: 10

  delta_gru_thresholds:
    encoder_tra_blocks: [null, null, null]   # order matches the 3 encoder GTConvBlocks (shallow->deep)
    decoder_tra_blocks: [null, null, null]   # order matches the first 3 decoder GTConvBlocks (deep->shallow)
    dpgrnn1:
      intra_rnn1: null
      intra_rnn2: null
      inter_rnn1: null
      inter_rnn2: null
    dpgrnn2:
      intra_rnn1: null
      intra_rnn2: null
      inter_rnn1: null
      inter_rnn2: null
